# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Procedure',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
