# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:58
from __future__ import unicode_literals

from django.db import migrations


def create_deductibles(apps, schema_editor):
	'''Create the initial set of deductibles.'''
	Deductible = apps.get_model('portal', 'deductible')
	Deductible.objects.get_or_create(value=0)
	Deductible.objects.get_or_create(value=5000)
	Deductible.objects.get_or_create(value=15000)


def create_titles(apps, schema_editor):
	'''Create the initial set of titles.'''
	Title = apps.get_model('portal', 'title')
	Title.objects.get_or_create(name='DC')
	Title.objects.get_or_create(name='DDS/DMD')
	Title.objects.get_or_create(name='DO')
	Title.objects.get_or_create(name='MD')
	Title.objects.get_or_create(name='Other')


class Migration(migrations.Migration):

	dependencies = [
		('portal', '0002_auto_20160917_1151'),
	]

	operations = [
		migrations.RunPython(
			code=create_deductibles,
			reverse_code=migrations.RunPython.noop
		),
		migrations.RunPython(
			code=create_titles,
			reverse_code=migrations.RunPython.noop
		),
	]
