# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:58
from __future__ import unicode_literals

from django.db import migrations


def create_states(apps, schema_editor):
	'''Create the initial set of states.'''
	State = apps.get_model('portal', 'state')

	newstates = [
		{'active': True, 'abbr': 'AZ', 'name': 'Arizona',},
		{'active': True, 'abbr': 'AR', 'name': 'Arkansas',},
		{'active': True, 'abbr': 'CA', 'name': 'California',},
		{'active': True, 'abbr': 'CO', 'name': 'Colorado',},
		{'active': True, 'abbr': 'CT', 'name': 'Connecticut',},
		{'active': True, 'abbr': 'DE', 'name': 'Delaware',},
		{'active': True, 'abbr': 'FL', 'name': 'Florida',},
		{'active': True, 'abbr': 'GA', 'name': 'Georgia',},
		{'active': True, 'abbr': 'HI', 'name': 'Hawaii',},
		{'active': True, 'abbr': 'IL', 'name': 'Illinois',},
		{'active': True, 'abbr': 'IN', 'name': 'Indiana',},
		{'active': True, 'abbr': 'KY', 'name': 'Kentucky',},
		{'active': True, 'abbr': 'MD', 'name': 'Maryland',},
		{'active': True, 'abbr': 'MI', 'name': 'Michigan',},
		{'active': True, 'abbr': 'NV', 'name': 'Nevada',},
		{'active': True, 'abbr': 'NJ', 'name': 'New Jersey',},
		{'active': True, 'abbr': 'NY', 'name': 'New York',},
		{'active': True, 'abbr': 'NC', 'name': 'North Carolina',},
		{'active': True, 'abbr': 'OH', 'name': 'Ohio',},
		{'active': True, 'abbr': 'OK', 'name': 'Oklahoma',},
		{'active': True, 'abbr': 'PA', 'name': 'Pennsylvania',},
		{'active': True, 'abbr': 'SC', 'name': 'South Carolina',},
		{'active': True, 'abbr': 'TN', 'name': 'Tennessee',},
		{'active': True, 'abbr': 'TX', 'name': 'Texas',},
		{'active': True, 'abbr': 'VA', 'name': 'Virginia',},
		{'active': True, 'abbr': 'WI', 'name': 'Wisconsin',},
		{'active': True, 'abbr': 'WV', 'name': 'West Virginia',},
	]

	for newstate in newstates:
		state, created = State.objects.get_or_create(**newstate)
		if created:
			print state.name


class Migration(migrations.Migration):

	dependencies = [
		('portal', '0003_data_deduct_title'),
	]

	operations = [
		migrations.RunPython(
			code=create_states,
			reverse_code=migrations.RunPython.noop
		),
	]
