# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:58
from __future__ import unicode_literals

from django.db import migrations


def connect_states_limits(apps, schema_editor):
	'''Connect States to thier liability Limits.'''
	State = apps.get_model('portal', 'state')
	Limit = apps.get_model('portal', 'limit')

	limit_100_300, x =   Limit.objects.get_or_create(min=100000,  max=300000)
	limit_200_600, x =   Limit.objects.get_or_create(min=200000,  max=600000)
	limit_300_900, x =   Limit.objects.get_or_create(min=300000,  max=900000)
	limit_250_500, x =   Limit.objects.get_or_create(min=250000,  max=500000)
	limit_250_750, x =   Limit.objects.get_or_create(min=250000,  max=750000)
	limit_500_1000, x =  Limit.objects.get_or_create(min=500000,  max=1000000)
	limit_500_1500, x =  Limit.objects.get_or_create(min=500000,  max=1500000)
	limit_750_1500, x =  Limit.objects.get_or_create(min=750000,  max=1500000)
	limit_1000_1000, x = Limit.objects.get_or_create(min=1000000, max=1000000)
	limit_1000_2000, x = Limit.objects.get_or_create(min=1000000, max=2000000)
	limit_1000_3000, x = Limit.objects.get_or_create(min=1000000, max=3000000)
	limit_1000_4000, x = Limit.objects.get_or_create(min=1000000, max=4000000)
	limit_1300_3900, x = Limit.objects.get_or_create(min=1300000, max=3900000)

	state = State.objects.get(abbr='AZ')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='AR')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='CA')
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='CO')
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='CT')
	state.limits.add(limit_100_300)
	state.limits.add(limit_250_750)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_4000)

	state = State.objects.get(abbr='DE')
	state.limits.add(limit_100_300)
	state.limits.add(limit_250_500)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_1000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='FL')
	state.limits.add(limit_250_750)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='GA')
	state.limits.add(limit_100_300)
	state.limits.add(limit_250_500)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_1000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='HI')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='IL')
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='IN')
	state.limits.add(limit_100_300)
	state.limits.add(limit_250_750)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='KY')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_500_1000)
	state.limits.add(limit_1000_1000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='MD')
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='MI')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_300_900)
	state.limits.add(limit_500_1000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='NC')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='NJ')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='NY')
	state.limits.add(limit_1000_3000)
	state.limits.add(limit_1300_3900)

	state = State.objects.get(abbr='NV')
	state.limits.add(limit_250_750)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='OH')
	state.limits.add(limit_250_750)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='OK')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_500_1000)
	state.limits.add(limit_1000_1000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='PA')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_250_750)
	state.limits.add(limit_500_1500)

	state = State.objects.get(abbr='SC')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='TN')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_500_1500)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='TX')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_300_900)
	state.limits.add(limit_500_1000)
	state.limits.add(limit_750_1500)
	state.limits.add(limit_1000_2000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='VA')
	state.limits.add(limit_100_300)
	state.limits.add(limit_200_600)
	state.limits.add(limit_500_1000)
	state.limits.add(limit_1000_1000)
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='WI')
	state.limits.add(limit_1000_3000)

	state = State.objects.get(abbr='WV')
	state.limits.add(limit_1000_3000)


class Migration(migrations.Migration):

	dependencies = [
		('portal', '0004_data_states'),
	]

	operations = [
		migrations.RunPython(
			code=connect_states_limits,
			reverse_code=migrations.RunPython.noop
		),
	]
