# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_data_connect_states_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductibleLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=5, default=1.0, max_digits=6)),
                ('deductible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Deductible')),
                ('limit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Limit')),
            ],
        ),
    ]
