# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 02:13
from __future__ import unicode_literals

from django.db import migrations


def add_florida_counties(apps, schema_editor):
	'''Add the Florida counties to the DB.'''
	State = apps.get_model('portal', 'state')
	County = apps.get_model('portal', 'county')
	FL = State.objects.get(abbr='FL')
	
	county, x = County.objects.get_or_create(name='Broward', territory='E')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='Clay', territory='D')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='Dade', territory='A')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='Duval', territory='D')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='Martin', territory='C')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='Palm Beach', territory='C')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='St. Johns', territory='D')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='St. Lucie', territory='C')
	FL.counties.add(county)
	county, x = County.objects.get_or_create(name='Remainder of State', territory='B')
	FL.counties.add(county)


def delete_florida_counties(apps, schema_editor):
	'''Remove the Florida counties from the DB.'''
	State = apps.get_model('portal', 'state')
	FL = State.objects.get(abbr='FL')
	for county in FL.counties.all():
		county.delete()


class Migration(migrations.Migration):

	dependencies = [
		('portal', '0008_auto_20160918_0212'),
	]

	operations = [
		migrations.RunPython(
			code=add_florida_counties,
			reverse_code=delete_florida_counties
		),
	]
