# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20160919_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickquote',
            old_name='primary_speciality',
            new_name='primary_specialty',
        ),
        migrations.RenameField(
            model_name='quickquote',
            old_name='secondary_speciality',
            new_name='secondary_specialty',
        ),
        migrations.AlterField(
            model_name='quickquote',
            name='cosmetic_surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Procedure'),
        ),
    ]
